### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by ssqgrand** [CartoDB/mobile-sdk#237]
python build-android.py --profile standard
CMake Deprecation Warning at /usr/share/cmake-3.10/Modules/CMakeForceCompiler.cmake:69 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/shisaiqun/workspace_as_stone/mobile-sdk/scripts/android-cmake/android.toolchain.cmake:1183 (CMAKE_FORCE_C_COMPILER)
  /home/shisaiqun/workspace_as_stone/mobile-sdk/build/android-x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:2 (project)

CMake Deprecation Warning at /usr/share/cmake-3.10/Modules/CMakeForceCompiler.cmake:83 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/shisaiqun/workspace_as_stone/mobile-sdk/scripts/android-cmake/android.toolchain.cmake:1195 (CMAKE_FORCE_CXX_COMPILER)
  /home/shisaiqun/workspace_as_stone/mobile-sdk/build/android-x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:2 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/shisaiqun/workspace_as_stone/mobile-sdk/build/android-x86_64/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "build-android.py", line 156, in <module>
    if not buildAndroidSO(args, abi):
  File "build-android.py", line 50, in buildAndroidSO
    '%s/scripts/build' % baseDir
  File "/home/shisaiqun/workspace_as_stone/mobile-sdk/scripts/build/sdk_build_utils.py", line 63, in cmake
    return execute(args.cmake, dir, *cmdArgs)
  File "/home/shisaiqun/workspace_as_stone/mobile-sdk/scripts/build/sdk_build_utils.py", line 58, in execute
    print("Error while executing %s (path %s):\n%s" % (cmd, dir, " ".join(cmdLine)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 16: ordinal not in range(128)

**Comment by mtehver** [comment]
I would like to reproduce that. Are you using the master branch? Which python version, what OS are you using? In CARTO we build iOS and Android platforms on OSX and UWP platform on Windows 10. We use Python 2.7.x.

**Comment by rexfordnyrk** [comment]
I faced same challenge using cmake 3.10.xxxxx like he is using but fixed it by using a previous version of cmake. Specifically 3.6.4111459. Leaving this here fo anyone who might face same issue.
you can specifiy your cmake path by using the --cmake option as so

`python build-android.py --profile standard --cmake /home/carto/Android/Sdk/cmake/3.6.4111459/bin/cmake`

**Comment by mtehver** [comment]
@rexfordnyrk Could you share the full error log? Are you using Linux/OSX? In both cases you should perhaps look at the files under scripts/travis repository. The code is configured to build Android SDK on Linux and iOS SDK on OSX, but could be easily changed.

**Comment by rexfordnyrk** [comment]
Yes I am running on linux specifically Fedora 28 & 29. Yes, I have seen those scripts, thanks for the pointers but I have managed to build successfully without that. All the same I will run those separately in a docker container and see. Please find below the error you encounter using cmake 3.10.xxx 
```

CMake Deprecation Warning at /home/carto/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeForceCompiler.cmake:69 (message
):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/carto/mobile-sdk/scripts/android-cmake/android.toolchain.cmake:1183 (CMAKE_FORCE_C_COMPILER)
  /home/carto/mobile-sdk/build/android-x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:2 (project) 


CMake Deprecation Warning at /home/carto/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeForceCompiler.cmake:83 (message
):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/carto/mobile-sdk/scripts/android-cmake/android.toolchain.cmake:1195 (CMAKE_FORCE_CXX_COMPILER)
  /home/carto/mobile-sdk/build/android-x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:2 (project) 


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably 
need to select a different build tool.
[root@a9ec426bd66b scripts]# python build-android.py --profile standard --cmake /home/carto/Android/Sdk/cmake/3.10.2.4988404/bin/cmake 
CMake Deprecation Warning at /home/carto/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeForceCompiler.cmake:69 (message):

  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/carto/mobile-sdk/scripts/android-cmake/android.toolchain.cmake:1183 (CMAKE_FORCE_C_COMPILER)
  /home/carto/mobile-sdk/build/android-x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:2 (project) 


CMake Deprecation Warning at /home/carto/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeForceCompiler.cmake:83 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  /home/carto/mobile-sdk/scripts/android-cmake/android.toolchain.cmake:1195 (CMAKE_FORCE_CXX_COMPILER)
  /home/carto/mobile-sdk/build/android-x86_64/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:2 (project) 

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/carto/mobile-sdk/build/android-x86_64/CMakeFiles/CMakeOutput.log".
Error while executing /home/carto/Android/Sdk/cmake/3.10.2.4988404/bin/cmake (path /home/carto/mobile-sdk/build/android-x86_64):
/home/carto/Android/Sdk/cmake/3.10.2.4988404/bin/cmake -DCMAKE_TOOLCHAIN_FILE=/home/carto/mobile-sdk/scripts/android-cmake/android.toolchain.cmake -DANDROID_NDK=/home/carto/Android/Sdk/ndk-bundle -DCMAKE_BUILD_TYPE=Release -DWRAPPER_DIR=/home/carto/mobile-sdk/generated/android-java/wrappers -DANDROID_TOOLCHAIN_NAME='x86_64-4.9' -DANDROID_ABI='x86_64' -DANDROID_STL='gnustl_static' -DANDROID_NATIVE_API_LEVEL='android-21' -DSDK_CPP_DEFINES=-D_CARTO_GEOCODING_SUPPORT -D_CARTO_WKBT_SUPPORT -D_CARTO_EDITABLE_SUPPORT -D_CARTO_SEARCH_SUPPORT -D_CARTO_PACKAGEMANAGER_SUPPORT -D_CARTO_CUSTOM_BASEMAP_SUPPORT -D_CARTO_ROUTING_SUPPORT -D_CARTO_OFFLINE_SUPPORT -DSDK_VERSION='|master|release/v4.1.6-6-ge7923d5' -DSDK_PLATFORM='Android' /home/carto/mobile-sdk/scripts/build
```
