### ISSUE TITLE
No implementation found

### ISSUE THREAD

**Issue by LordArianz** [CartoDB/mobile-sdk#337]
Hi, I faced this error when I create WKTGeometryReader:
`WKTGeometryReader reader = new WKTGeometryReader();`

```E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.test, PID: 7001
    java.lang.UnsatisfiedLinkError: No implementation found for long com.carto.geometry.WKTGeometryReaderModuleJNI.new_WKTGeometryReader() (tried Java_com_carto_geometry_WKTGeometryReaderModuleJNI_new_1WKTGeometryReader and Java_com_carto_geometry_WKTGeometryReaderModuleJNI_new_1WKTGeometryReader__)
        at com.carto.geometry.WKTGeometryReaderModuleJNI.new_WKTGeometryReader(Native Method)
        at com.carto.geometry.WKTGeometryReader.<init>(WKTGeometryReader.java:49)
```

**Comment by mtehver** [comment]
Most likely the native library is not yet loaded. Have you called MapView.registerLicense?

**Comment by LordArianz** [comment]
Thanks
